### ISSUE TITLE
Data_Transformation - message_data

### ISSUE THREAD

**Issue by falberto** [rorysroes/SGX-Full-OrderBook-Tick-Data-Trading-Strategy#3]
Hi,
I am trying to reproduce your model but I am having difficulty understanding the meaning in the columns in the CN_Futures_2014.01.02 file.

As I understand this file is the Extraction from the Limited Order Book, but I couldn't understand the QuantityDifference columns (would it be the difference between the limited ask quantity minus the limited bid quantity?) and the BestQuantity column.

I also noticed that in the file there are many repeated OrderNumber for different timestamps.

Thank's for your time.

**Comment by akhaleel** [comment]
Its kind of hard to articulate over an email, but i'd gladly discuss it
with you over skype, if you'd like.  Do you currently run any successful ai
trading algorithms?

**Comment by falberto** [comment]
Lets discuss then.

Are you from Brazil?

Send me an email: felipealberto@gmail.com

Em ter, 3 de dez de 2019 13:32, akhaleel <notifications@github.com>
escreveu:

> Its kind of hard to articulate over an email, but i'd gladly discuss it
> with you over skype, if you'd like. Do you currently run any successful ai
> trading algorithms?
>

**Comment by akhaleel** [comment]
No sir, I live in the united States.  I run a proprietary AI trading firm
and I also work for another AI company.

Are you currently trading?

**Comment by xiandong79** [comment]
@falberto it seems that you are planning to do something on `trading`, especially `cryptocurrrency trading`.

@akhaleel `b6d3cd7b10ccdb46`is my skype name. we can set up a skype group

**Comment by akhaleel** [comment]
I’d love to collaborate with you guys.  I’ve spent the last 2 years working
at Vectorspace.ai, which is where I learned AI.  The firm is led by former
Lawrence Berkeley Lab researchers.  We predominantly focus on NLP/NLU.
Below is an article that gives an example of how profitable our trading
model is.

https://medium.com/hackernoon/profiting-from-information-arbitrage-in-the-financial-markets-3abfca9806d8

I also have a small team of traders that predominately work remotely.  All
strategies we deploy are intraday AI trading algorithms.

I’ve been a derivates trader for 19 years now.  I’ll be leaving Vectorspace
soon.  I have a new startup I’m looking into.

Nonetheless you can reach me on Skype @akhaleel.
